branch-defaults:
  master:
    environment: agile-codewell-server
    group_suffix: null
deploy:
  artifact: target/server.jar
environment-defaults:
  agile-codewell-server:
    branch: null
    repository: null
global:
  application_name: codewell-server
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: 3.1.7
  profile: null
  repository: null
  sc: git
  workspace_type: Application
