version: 2.1
orbs:
  ebs: circleci/aws-elastic-beanstalk@1.0.1
jobs:
  Compile:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: Compile Java code
          command: mvn compile
  Run Unit Tests:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run JUnit Tests
          command: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
  Package JAR:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Compile into JAR and save in ./target folder
          command: mvn clean package -Dmaven.test.skip=true
      - persist_to_workspace:
          root: ./
          paths:
            - target
  Deploy to EBS:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ebs/setup
      - attach_workspace:
          at: ./
      - run:
          name: Deploy JAR
          command: eb deploy $EBS_ENV
workflows:
  Test and Deploy:
    jobs:
      - Compile
      - Run Unit Tests:
          requires:
            - Compile
      - Package JAR:
          requires:
            - Run Unit Tests
      - Deploy to EBS:
          requires:
            - Package JAR
          filters:
            branches:
              only: master