version: 2
jobs:
  Compile:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: Compile Java code
          command: mvn compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  Run Unit Tests:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run JUnit Tests
          command: mvn test
#  Package JAR:
#    docker:
#      - image: circleci/openjdk:11.0.3-jdk-stretch
#    steps:
#      - checkout
#      - run:
#          command: mvn clean package -Dmaven.test.skip=true
#      - persist_to_workspace:
#          root: ~/
#          paths:
#            - target/
workflows:
  version: 2
  Test and Deploy:
    jobs:
      - Compile
      - Run Unit Tests:
          requires:
            - Compile
#      - Package JAR:
#          requires:
#            - Run Unit Tests