orbs: # declare what orbs we are going to use
  node: circleci/node@10.16.0 # the node orb provides common node-related configuration 

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm test